name: to_do_list
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-231.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
